In [ ]:
import pandas as pd
transactions=pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\analytics-project\datasets\bank_transactions.csv")
customer=pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\analytics-project\datasets\customers_master.csv")


print("transactions shape ",transactions.shape)
print("customer shape ",customer.shape)

transactions shape  (60000, 10)
customer shape  (3000, 7)

In [216]:
loan=pd.read_csv(r"C:\Users\Asus\OneDrive\Desktop\analytics-project\datasets\loan_info.csv")

In [162]:
import numpy as np

In [163]:
print("transactions preview:")
transactions.head()

transactions preview:

,transaction_id,customer_id,customer_name,transaction_date,amount,merchant_category,payment_mode,city,account_type,transaction_status
0,TXN0048352,CUST000718,Kavya Nair,2023-01-01 03:38:02,782.88,Dining,UPI,Vadodara,Salary,Success
1,TXN0042984,CUST001604,Neha Gupta,2023-01-01 04:37:17,3886.42,Fuel,UPI,Ahmedabad,Savings,Success
2,TXN0041420,CUST000801,Vihaan Reddy,2023-01-01 06:36:44,18743.82,Insurance/EMI,Credit Card,Chennai,Savings,Success
3,TXN0018479,CUST002258,Sai Pillai,2023-01-01 07:19:15,3380.00,Groceries,Credit Card,Jaipur,Salary,Success
4,TXN0031367,CUST001555,Anika Agarwal,2023-01-01 08:03:34,892.14,Groceries,UPI,Kanpur,Salary,Success

In [164]:


print("customer preview:")
customer.head()

customer preview:

,customer_id,customer_name,city,account_type,income_segment,join_date,activity_level
0,CUST000001,Aarav Singh,Hyderabad,Current,Mid,2021-07-19,Medium
1,CUST000002,Arjun Reddy,Pune,Savings,Mid,2019-02-16,Low
2,CUST000003,Aditya Pillai,Patna,Salary,Low,2020-07-21,Medium
3,CUST000004,Aarav Iyer,Delhi,Savings,High,2021-09-11,High
4,CUST000005,Anika Bose,Pune,Savings,High,2022-10-09,Low

In [165]:
transactions.columns
customer.columns

Index(['customer_id', 'customer_name', 'city', 'account_type',
       'income_segment', 'join_date', 'activity_level'],
      dtype='str')

In [166]:
print('transactions datatypes : ')
print(transactions.dtypes)

print('customer datatypes : ')
print(customer.dtypes)

transactions datatypes :
transaction_id            str
customer_id               str
customer_name             str
transaction_date          str
amount                float64
merchant_category         str
payment_mode              str
city                      str
account_type              str
transaction_status        str
dtype: object
customer datatypes :
customer_id       str
customer_name     str
city              str
account_type      str
income_segment    str
join_date         str
activity_level    str
dtype: object

In [167]:
transactions['transaction_date']=pd.to_datetime(
    transactions['transaction_date']
)

customer['join_date']=pd.to_datetime(
    customer['join_date']
)

In [168]:
#missing values check
transactions.isna().sum()
customer.isna().sum()

customer_id       0
customer_name     0
city              0
account_type      0
income_segment    0
join_date         0
activity_level    0
dtype: int64

In [169]:
transactions.duplicated().sum()
customer.duplicated().sum()

np.int64(0)

In [170]:
print(transactions.shape[0])
print(transactions['transaction_id'].nunique())

print(customer.shape[0])
print(customer['customer_id'].nunique())

60000
60000
3000
3000

In [171]:
total_successful_transactions_amount=transactions[transactions['transaction_status']=='Success']['amount'].sum()
print(total_successful_transactions_amount)

total_successful_transactions_count=transactions[transactions['transaction_status']=='Success']['transaction_id'].count()
print(total_successful_transactions_count)

avg_successful_transactions_amount=transactions[transactions['transaction_status']=='Success']['amount'].mean()
print(avg_successful_transactions_amount)

671460125.3899999
58145
11548.028642015648

In [172]:
total_successful_transactions_count=transactions[transactions['transaction_status']=='Success']['transaction_id'].count()
percentage_success=(total_successful_transactions_count/transactions['transaction_id'].count())*100
print(percentage_success)

96.90833333333333

In [173]:
transactions['month_no']=transactions['transaction_date'].dt.month
transactions['month']=transactions['transaction_date'].dt.month_name()
transactions['year']=transactions['transaction_date'].dt.year
success_tr=transactions[transactions['transaction_status']=='Success'].copy()
year_month_wise_analysis=success_tr.groupby(['year','month_no','month'])['amount'].agg(['sum','mean','count']).sort_index()

year_month_wise_analysis

                                 sum          mean  count
year month_no month
2023 1        January    26231977.62  10624.535286   2469
     2        February   24081966.53  10794.247660   2231
     3        March      26202584.38  10625.541111   2466
     4        April      27893220.18  11661.045226   2392
     5        May        29829001.69  12018.131221   2482
     6        June       26600634.32  10530.734093   2526
     7        July       30162395.13  11860.949717   2543
     8        August     24900907.15  10268.415320   2425
     9        September  23677226.51  10019.985827   2363
     10       October    36153813.37  14684.733294   2462
     11       November   33009095.55  14271.117834   2313
     12       December   30286907.11  12242.080481   2474
2024 1        January    25736877.51  10652.681089   2416
     2        February   23659762.22  10282.382538   2301
     3        March      26814036.56  10948.973687   2449
     4        April      24672710.36  10432.435670   2365
     5        May        27667027.47  11437.382170   2419
     6        June       26554158.26  11304.452218   2349
     7        July       25668802.36  10346.151697   2481
     8        August     26800770.39  10673.345436   2511
     9        September  24286430.44  10225.865448   2375
     10       October    34356002.87  13720.448431   2504
     11       November   35496642.41  14674.097730   2419
     12       December   30717175.00  12745.715768   2410

In [174]:
merchant_category_analysis=success_tr.groupby(['merchant_category'])['amount'].agg(['sum','count']).sort_values('sum',ascending=False)

In [175]:
payment_analysis=success_tr.groupby('payment_mode')['amount'].agg(['sum','count','mean']).sort_values('sum',ascending=False)
payment_analysis["transaction_count_percentage"]=(payment_analysis['count']/total_successful_transactions_count)*100
payment_analysis

                       sum  count          mean  transaction_count_percentage
payment_mode
UPI           2.787478e+08  24466  11393.272360                     42.077565
Debit Card    1.505380e+08  12776  11782.876198                     21.972655
Credit Card   1.096732e+08   9350  11729.750566                     16.080488
NEFT/IMPS     6.736759e+07   5760  11695.762790                      9.906269
Net Banking   6.513354e+07   5793  11243.489739                      9.963023

In [176]:
city_analysis=success_tr.groupby('city')['amount'].agg(['sum','count']).sort_values('sum',ascending=False).head(10)

In [177]:
account_type_analysis=success_tr.groupby('account_type')['amount'].agg(['sum','count','mean']).sort_values('sum',ascending=False)
account_type_analysis

                       sum  count          mean
account_type
Savings       3.855820e+08  32978  11692.098244
Salary        2.247925e+08  19724  11396.902192
Current       6.108561e+07   5443  11222.783511

In [178]:
transactions_status_by_payment_mode=transactions.pivot_table(index='payment_mode',columns='transaction_status',values='transaction_id',aggfunc='count')
transactions_status_by_payment_mode

transaction_status  Failed  Success
payment_mode
Credit Card            319     9350
Debit Card             415    12776
NEFT/IMPS              193     5760
Net Banking            159     5793
UPI                    769    24466

In [179]:
monthly_transaction_trend_status=transactions.pivot_table(index=['year','month_no','month'],columns='transaction_status',values='transaction_id',aggfunc='count').sort_index()
monthly_transaction_trend_status

transaction_status       Failed  Success
year month_no month
2023 1        January        65     2469
     2        February       76     2231
     3        March          71     2466
     4        April          76     2392
     5        May            83     2482
     6        June           81     2526
     7        July           89     2543
     8        August         73     2425
     9        September      78     2363
     10       October        66     2462
     11       November       88     2313
     12       December       79     2474
2024 1        January        93     2416
     2        February       75     2301
     3        March          73     2449
     4        April          75     2365
     5        May            70     2419
     6        June           83     2349
     7        July           73     2481
     8        August         79     2511
     9        September      78     2375
     10       October        73     2504
     11       November       82     2419
     12       December       76     2410

In [180]:
customer_activity_analysis=success_tr.groupby(['customer_id','customer_name'])['amount'].agg(['sum','count']).sort_values('sum',ascending=False)
customer_activity_analysis

                                  sum  count
customer_id customer_name
CUST000012  Isha Singh     2735933.38     48
CUST002454  Vihaan Patel   2304425.32     23
CUST002840  Saanvi Joshi   2074959.21     36
CUST001438  Diya Kapoor    2050285.42     48
CUST001053  Vivaan Mehta   1871177.73     29
...                               ...    ...
CUST001743  Sonal Sharma      6626.81      5
CUST000365  Ishaan Desai      5792.28      2
CUST001625  Arjun Agarwal     4245.68      2
CUST000659  Anika Bansal      4213.06      4
CUST000111  Kavya Joshi       3864.02      2

[2999 rows x 2 columns]

In [181]:
no_of_active_customer=success_tr['customer_id'].nunique()
no_of_active_customer
city_wise_active_customer=success_tr.groupby('city').agg(
    active_customer=('customer_id','nunique'),
    total_amount=('amount','sum')
)
city_wise_active_customer

            active_customer  total_amount
city
Ahmedabad               153   36283476.73
Bengaluru               123   36239476.97
Bhopal                  136   25314573.83
Chandigarh              180   43054847.63
Chennai                 153   35373881.01
Coimbatore              171   41637130.40
Delhi                   151   36831759.29
Hyderabad               144   35203267.15
Indore                  147   24956279.69
Jaipur                  148   35527499.55
Kanpur                  136   29100942.59
Kolkata                 147   29233671.25
Lucknow                 164   30847111.04
Ludhiana                150   30836844.05
Mumbai                  108   25397842.80
Nagpur                  152   30033729.42
Patna                   164   29457665.76
Pune                    152   37911435.53
Surat                   159   37904390.57
Vadodara                161   40314300.13

In [182]:
account_wise_active_cust_analysis=success_tr.groupby('account_type').agg(
    active_customer=('customer_id','nunique'),
    total_amount=('amount','sum'),
    avg_amount=('amount','mean')
)
account_wise_active_cust_analysis

              active_customer  total_amount    avg_amount
account_type
Current                   297  6.108561e+07  11222.783511
Salary                    989  2.247925e+08  11396.902192
Savings                  1713  3.855820e+08  11692.098244

In [183]:
joined_table=success_tr.merge(customer[["customer_id", "income_segment"]],on='customer_id',how='left')
income_segment_analysis=joined_table.groupby('income_segment')['amount'].agg(['count','sum','mean'])
income_segment_analysis

                count           sum          mean
income_segment
High            13078  2.311621e+08  17675.649260
Low             19858  1.139738e+08   5739.440806
Mid             20872  1.994253e+08   9554.682471
Premium          4337  1.268988e+08  29259.588730

In [184]:
income_segment_vs_customer_activity=joined_table.groupby('income_segment').agg(
    active_customer=('customer_id','nunique'),
    total_transactions=('amount','sum'),
    avg_transactions=('amount','mean')
)
income_segment_analysis

                count           sum          mean
income_segment
High            13078  2.311621e+08  17675.649260
Low             19858  1.139738e+08   5739.440806
Mid             20872  1.994253e+08   9554.682471
Premium          4337  1.268988e+08  29259.588730

In [185]:
success_tr['day']=success_tr['transaction_date'].dt.day_name()
success_tr['day_no']=success_tr['transaction_date'].dt.day_of_week

most_transactioned_day_of_week=success_tr.groupby(['day_no','day'])['amount'].sum()
most_transactioned_day_of_week

day_no  day
0       Monday       9.715427e+07
1       Tuesday      9.588794e+07
2       Wednesday    9.476022e+07
3       Thursday     1.005850e+08
4       Friday       9.519402e+07
5       Saturday     9.048750e+07
6       Sunday       9.739120e+07
Name: amount, dtype: float64

In [186]:
weekday_wise_analysis=success_tr.groupby(['day_no','day'])['amount'].agg(['count','sum','mean'])
weekday_wise_analysis

                  count           sum          mean
day_no day
0      Monday      8320  9.715427e+07  11677.195582
1      Tuesday     8207  9.588794e+07  11683.677710
2      Wednesday   8202  9.476022e+07  11553.307092
3      Thursday    8361  1.005850e+08  12030.255523
4      Friday      8319  9.519402e+07  11442.964689
5      Saturday    8322  9.048750e+07  10873.287687
6      Sunday      8414  9.739120e+07  11574.899049

In [187]:
temp1=transactions.pivot_table(index='payment_mode',columns='transaction_status',values='transaction_id',aggfunc='count')
temp1['failure_rate']=(temp1['Failed']/(temp1['Failed']+temp1['Success']))*100
payment_vs_transaction_status_analysis=temp1.sort_values('failure_rate',ascending=False)
payment_vs_transaction_status_analysis

transaction_status  Failed  Success  failure_rate
payment_mode
Credit Card            319     9350      3.299204
NEFT/IMPS              193     5760      3.242063
Debit Card             415    12776      3.146084
UPI                    769    24466      3.047355
Net Banking            159     5793      2.671371

In [188]:
month_merchant_category_analysis=success_tr.groupby(['month_no','month','merchant_category'])['amount'].sum()
month_merchant_category_analysis

month_no  month     merchant_category
1         January   ATM Withdrawal        2132772.74
                    Dining                2109775.15
                    Education             5059725.45
                    Electronics          10687248.08
                    Entertainment         1247233.76
                                            ...
12        December  Healthcare            5633984.45
                    Insurance/EMI         5438483.26
                    Shopping              7350877.35
                    Travel                9431679.85
                    Utilities             1873117.00
Name: amount, Length: 144, dtype: float64

In [189]:
account_type_and_payment_mode=success_tr.groupby(['account_type','payment_mode'])['amount'].agg(['sum','count'])
account_type_and_payment_mode

                                    sum  count
account_type payment_mode
Current      Credit Card   9.284632e+06    852
             Debit Card    1.499450e+07   1192
             NEFT/IMPS     5.512578e+06    485
             Net Banking   5.452375e+06    548
             UPI           2.584153e+07   2366
Salary       Credit Card   3.616234e+07   3168
             Debit Card    4.969098e+07   4405
             NEFT/IMPS     2.305735e+07   1973
             Net Banking   1.976972e+07   1966
             UPI           9.611211e+07   8212
Savings      Credit Card   6.422619e+07   5330
             Debit Card    8.585255e+07   7179
             NEFT/IMPS     3.879767e+07   3302
             Net Banking   3.991144e+07   3279
             UPI           1.567942e+08  13888

In [190]:
#recency
def sort(group):
    return group.sort_values(['year','month_no','day_no'],ascending=[False,False,False])
latest_transactions=success_tr.groupby(['customer_id','customer_name']).apply(sort).groupby(level=["customer_id", "customer_name"]).head(1)
latest_transactions['recency']=(pd.Timestamp.today()-latest_transactions['transaction_date']).dt.days
latest_transactions

,,,transaction_id,transaction_date,amount,merchant_category,payment_mode,city,account_type,transaction_status,month_no,month,year,day,day_no,recency
customer_id,customer_name,,,,,,,,,,,,,,,
CUST000001,Aarav Singh,55730,TXN0049025,2024-11-09 21:33:45,1058.47,Groceries,Debit Card,Hyderabad,Current,Success,11,November,2024,Saturday,5,672
CUST000002,Arjun Reddy,51534,TXN0023020,2024-09-20 12:05:34,2758.70,Utilities,Debit Card,Pune,Savings,Success,9,September,2024,Friday,4,723
CUST000003,Aditya Pillai,55993,TXN0058312,2024-11-13 11:01:02,2062.51,Utilities,NEFT/IMPS,Patna,Salary,Success,11,November,2024,Wednesday,2,669
CUST000004,Aarav Iyer,55910,TXN0026904,2024-11-12 09:49:44,59139.45,Travel,NEFT/IMPS,Delhi,Savings,Success,11,November,2024,Tuesday,1,670
CUST000005,Anika Bose,58149,TXN0040736,2024-12-08 14:36:17,6131.40,Groceries,UPI,Pune,Savings,Success,12,December,2024,Sunday,6,643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CUST002996,Nikhil Nair,57601,TXN0013608,2024-12-01 22:12:56,396.68,Dining,Net Banking,Mumbai,Savings,Success,12,December,2024,Sunday,6,650
CUST002997,Myra Nair,58506,TXN0021308,2024-12-12 16:43:07,6248.19,Groceries,NEFT/IMPS,Ludhiana,Salary,Success,12,December,2024,Thursday,3,639
CUST002998,Isha Pillai,57956,TXN0027852,2024-12-05 19:51:26,3250.54,Dining,Debit Card,Pune,Savings,Success,12,December,2024,Thursday,3,646
CUST002999,Aarav Reddy,58095,TXN0015702,2024-12-07 17:42:57,3480.02,Shopping,Credit Card,Chennai,Savings,Success,12,December,2024,Saturday,5,644
CUST003000,Rohan Bansal,59578,TXN0047761,2024-12-25 19:14:28,5751.56,Fuel,UPI,Bengaluru,Savings,Success,12,December,2024,Wednesday,2,626

In [191]:
#frequency
frequency=success_tr.groupby(['customer_id','customer_name'])['transaction_id'].count()
frequency

customer_id  customer_name
CUST000001   Aarav Singh      24
CUST000002   Arjun Reddy       4
CUST000003   Aditya Pillai    20
CUST000004   Aarav Iyer       39
CUST000005   Anika Bose        8
                              ..
CUST002996   Nikhil Nair      46
CUST002997   Myra Nair        14
CUST002998   Isha Pillai      14
CUST002999   Aarav Reddy       5
CUST003000   Rohan Bansal     32
Name: transaction_id, Length: 2999, dtype: int64

In [192]:
#monetary
monetary=success_tr.groupby(['customer_id','customer_name'])['amount'].sum()
monetary

customer_id  customer_name
CUST000001   Aarav Singh      182689.58
CUST000002   Arjun Reddy       48277.29
CUST000003   Aditya Pillai     94191.66
CUST000004   Aarav Iyer       868844.12
CUST000005   Anika Bose       190502.25
                                ...
CUST002996   Nikhil Nair      405419.86
CUST002997   Myra Nair        298524.78
CUST002998   Isha Pillai      111345.58
CUST002999   Aarav Reddy       21229.55
CUST003000   Rohan Bansal     987234.40
Name: amount, Length: 2999, dtype: float64

In [193]:
rfm=latest_transactions.merge(
    frequency,
    on=['customer_id','customer_name']
).merge(
    monetary,
    on=['customer_id','customer_name']
)

rfm.rename(
    columns={'transaction_id_y':'frequency','amount_y':'monetary'},
    inplace=True
)
rfm

,,transaction_id_x,transaction_date,amount_x,merchant_category,payment_mode,city,account_type,transaction_status,month_no,month,year,day,day_no,recency,frequency,monetary
customer_id,customer_name,,,,,,,,,,,,,,,,
CUST000001,Aarav Singh,TXN0049025,2024-11-09 21:33:45,1058.47,Groceries,Debit Card,Hyderabad,Current,Success,11,November,2024,Saturday,5,672,24,182689.58
CUST000002,Arjun Reddy,TXN0023020,2024-09-20 12:05:34,2758.70,Utilities,Debit Card,Pune,Savings,Success,9,September,2024,Friday,4,723,4,48277.29
CUST000003,Aditya Pillai,TXN0058312,2024-11-13 11:01:02,2062.51,Utilities,NEFT/IMPS,Patna,Salary,Success,11,November,2024,Wednesday,2,669,20,94191.66
CUST000004,Aarav Iyer,TXN0026904,2024-11-12 09:49:44,59139.45,Travel,NEFT/IMPS,Delhi,Savings,Success,11,November,2024,Tuesday,1,670,39,868844.12
CUST000005,Anika Bose,TXN0040736,2024-12-08 14:36:17,6131.40,Groceries,UPI,Pune,Savings,Success,12,December,2024,Sunday,6,643,8,190502.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CUST002996,Nikhil Nair,TXN0013608,2024-12-01 22:12:56,396.68,Dining,Net Banking,Mumbai,Savings,Success,12,December,2024,Sunday,6,650,46,405419.86
CUST002997,Myra Nair,TXN0021308,2024-12-12 16:43:07,6248.19,Groceries,NEFT/IMPS,Ludhiana,Salary,Success,12,December,2024,Thursday,3,639,14,298524.78
CUST002998,Isha Pillai,TXN0027852,2024-12-05 19:51:26,3250.54,Dining,Debit Card,Pune,Savings,Success,12,December,2024,Thursday,3,646,14,111345.58
CUST002999,Aarav Reddy,TXN0015702,2024-12-07 17:42:57,3480.02,Shopping,Credit Card,Chennai,Savings,Success,12,December,2024,Saturday,5,644,5,21229.55
CUST003000,Rohan Bansal,TXN0047761,2024-12-25 19:14:28,5751.56,Fuel,UPI,Bengaluru,Savings,Success,12,December,2024,Wednesday,2,626,32,987234.40

In [194]:
rfm['R_score']=pd.qcut(
    rfm['recency'],
    5,
    labels=[5,4,3,2,1]
)
rfm['F_score'] = pd.qcut(
    rfm['frequency'],
    5,
    labels=[1, 2, 3, 4, 5]
)
rfm['M_score'] = pd.qcut(
    rfm['monetary'],
    5,
    labels=[1, 2, 3, 4, 5]
)
rfm['RFM_Score']=rfm['R_score'].astype(str)+rfm['F_score'].astype(str)+rfm['M_score'].astype(str)
rfm

,,transaction_id_x,transaction_date,amount_x,merchant_category,payment_mode,city,account_type,transaction_status,month_no,month,year,day,day_no,recency,frequency,monetary,R_score,F_score,M_score,RFM_Score
customer_id,customer_name,,,,,,,,,,,,,,,,,,,,
CUST000001,Aarav Singh,TXN0049025,2024-11-09 21:33:45,1058.47,Groceries,Debit Card,Hyderabad,Current,Success,11,November,2024,Saturday,5,672,24,182689.58,2,4,3,243
CUST000002,Arjun Reddy,TXN0023020,2024-09-20 12:05:34,2758.70,Utilities,Debit Card,Pune,Savings,Success,9,September,2024,Friday,4,723,4,48277.29,1,1,1,111
CUST000003,Aditya Pillai,TXN0058312,2024-11-13 11:01:02,2062.51,Utilities,NEFT/IMPS,Patna,Salary,Success,11,November,2024,Wednesday,2,669,20,94191.66,2,4,2,242
CUST000004,Aarav Iyer,TXN0026904,2024-11-12 09:49:44,59139.45,Travel,NEFT/IMPS,Delhi,Savings,Success,11,November,2024,Tuesday,1,670,39,868844.12,2,5,5,255
CUST000005,Anika Bose,TXN0040736,2024-12-08 14:36:17,6131.40,Groceries,UPI,Pune,Savings,Success,12,December,2024,Sunday,6,643,8,190502.25,4,1,3,413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CUST002996,Nikhil Nair,TXN0013608,2024-12-01 22:12:56,396.68,Dining,Net Banking,Mumbai,Savings,Success,12,December,2024,Sunday,6,650,46,405419.86,3,5,5,355
CUST002997,Myra Nair,TXN0021308,2024-12-12 16:43:07,6248.19,Groceries,NEFT/IMPS,Ludhiana,Salary,Success,12,December,2024,Thursday,3,639,14,298524.78,4,2,4,424
CUST002998,Isha Pillai,TXN0027852,2024-12-05 19:51:26,3250.54,Dining,Debit Card,Pune,Savings,Success,12,December,2024,Thursday,3,646,14,111345.58,3,2,2,322
CUST002999,Aarav Reddy,TXN0015702,2024-12-07 17:42:57,3480.02,Shopping,Credit Card,Chennai,Savings,Success,12,December,2024,Saturday,5,644,5,21229.55,4,1,1,411
CUST003000,Rohan Bansal,TXN0047761,2024-12-25 19:14:28,5751.56,Fuel,UPI,Bengaluru,Savings,Success,12,December,2024,Wednesday,2,626,32,987234.40,5,5,5,555

In [195]:
rfm['segment'] = np.select(
    [
        (rfm['R_score'].astype(int) >= 4) &
        (rfm['F_score'].astype(int) >= 4) &
        (rfm['M_score'].astype(int) >= 4),

        (rfm['R_score'].astype(int) >= 3) &
        (rfm['F_score'].astype(int) >= 4) &
        (rfm['M_score'].astype(int) >= 3),

        (rfm['R_score'].astype(int) >= 4) &
        (rfm['F_score'].astype(int) <= 3),

        (rfm['R_score'].astype(int) <= 2) &
        (rfm['F_score'].astype(int) >= 3),

        (rfm['R_score'].astype(int) <= 2) &
        (rfm['F_score'].astype(int) <= 2)
    ],
    [
        'Champions',
        'Loyal Customers',
        'Potential Loyalists',
        'At Risk Customers',
        'Lost Customers'
    ],
    default='Regular Customers'
) 

rfm['segment'].value_counts()

segment
Lost Customers         713
Potential Loyalists    572
At Risk Customers      480
Champions              425
Regular Customers      420
Loyal Customers        389
Name: count, dtype: int64

In [198]:
no_of_unique_customer=transactions['customer_id'].nunique()
no_of_unique_customer

2999

In [205]:
segment_analysis=rfm.groupby('segment').agg(
    no_of_customer=('transaction_id_x','nunique'),
    total_amount_per_segment=('amount_x','sum'),
    avg_amount_per_segment=('amount_x','mean')
)
segment_analysis['customer_contribution_per_segment']=(segment_analysis['no_of_customer']/no_of_unique_customer)*100
segment_analysis['amount_contribution_per_segment']=(segment_analysis['total_amount_per_segment']/segment_analysis['total_amount_per_segment'].sum())*100

segment_analysis

,no_of_customer,total_amount_per_segment,avg_amount_per_segment,customer_contribution_per_segment,amount_contribution_per_segment
segment,,,,,
At Risk Customers,480,6686279.28,13929.748500,16.005335,17.030395
Champions,425,7719060.16,18162.494494,14.171390,19.660956
Lost Customers,713,8327840.50,11680.000701,23.774592,21.211560
Loyal Customers,389,4804977.92,12352.128329,12.970990,12.238596
Potential Loyalists,572,7049804.99,12324.833899,19.073024,17.956319
Regular Customers,420,4672896.21,11125.943357,14.004668,11.902175

In [1]:
highest_value_customer=rfm.sort_values('monetary',ascending=False).head(10)
highest_value_customer=highest_value_customer.reset_index()

NameError: name 'rfm' is not defined

In [206]:
rfm

,,transaction_id_x,transaction_date,amount_x,merchant_category,payment_mode,city,account_type,transaction_status,month_no,month,...,day,day_no,recency,frequency,monetary,R_score,F_score,M_score,RFM_Score,segment
customer_id,customer_name,,,,,,,,,,,,,,,,,,,,,
CUST000001,Aarav Singh,TXN0049025,2024-11-09 21:33:45,1058.47,Groceries,Debit Card,Hyderabad,Current,Success,11,November,...,Saturday,5,672,24,182689.58,2,4,3,243,At Risk Customers
CUST000002,Arjun Reddy,TXN0023020,2024-09-20 12:05:34,2758.70,Utilities,Debit Card,Pune,Savings,Success,9,September,...,Friday,4,723,4,48277.29,1,1,1,111,Lost Customers
CUST000003,Aditya Pillai,TXN0058312,2024-11-13 11:01:02,2062.51,Utilities,NEFT/IMPS,Patna,Salary,Success,11,November,...,Wednesday,2,669,20,94191.66,2,4,2,242,At Risk Customers
CUST000004,Aarav Iyer,TXN0026904,2024-11-12 09:49:44,59139.45,Travel,NEFT/IMPS,Delhi,Savings,Success,11,November,...,Tuesday,1,670,39,868844.12,2,5,5,255,At Risk Customers
CUST000005,Anika Bose,TXN0040736,2024-12-08 14:36:17,6131.40,Groceries,UPI,Pune,Savings,Success,12,December,...,Sunday,6,643,8,190502.25,4,1,3,413,Potential Loyalists
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CUST002996,Nikhil Nair,TXN0013608,2024-12-01 22:12:56,396.68,Dining,Net Banking,Mumbai,Savings,Success,12,December,...,Sunday,6,650,46,405419.86,3,5,5,355,Loyal Customers
CUST002997,Myra Nair,TXN0021308,2024-12-12 16:43:07,6248.19,Groceries,NEFT/IMPS,Ludhiana,Salary,Success,12,December,...,Thursday,3,639,14,298524.78,4,2,4,424,Potential Loyalists
CUST002998,Isha Pillai,TXN0027852,2024-12-05 19:51:26,3250.54,Dining,Debit Card,Pune,Savings,Success,12,December,...,Thursday,3,646,14,111345.58,3,2,2,322,Regular Customers
CUST002999,Aarav Reddy,TXN0015702,2024-12-07 17:42:57,3480.02,Shopping,Credit Card,Chennai,Savings,Success,12,December,...,Saturday,5,644,5,21229.55,4,1,1,411,Potential Loyalists
CUST003000,Rohan Bansal,TXN0047761,2024-12-25 19:14:28,5751.56,Fuel,UPI,Bengaluru,Savings,Success,12,December,...,Wednesday,2,626,32,987234.40,5,5,5,555,Champions

In [223]:
#loan analysis
total_loan_applications=loan['loan_id'].nunique()
total_requested_loan_amount=loan['requested_loan_amount'].sum()
total_approved_loan_amount=loan['approved_loan_amount'].sum()

In [ ]:
loan_status_info=loan['loan_status'].value_counts()

loan_status
Approved    6538
Rejected    1454
Pending        8
Name: count, dtype: int64

In [229]:
loan_category_analysis=loan.groupby('loan_type').agg(
    no_of_applications=('loan_id','count'),
    total_req_loan_categorywise=('requested_loan_amount','sum'),
    total_app_loan_categorywise=('approved_loan_amount','sum')
).sort_values('no_of_applications',ascending=False)
loan_category_analysis

,no_of_applications,total_req_loan_categorywise,total_app_loan_categorywise
loan_type,,,
Personal,2537,9.815678e+08,6.933193e+08
Home,1445,5.024072e+09,3.656791e+09
Vehicle,1237,1.110216e+09,7.833395e+08
Business,1168,1.878671e+09,1.362702e+09
Education,950,9.885586e+08,6.986685e+08
Gold,663,1.608276e+08,1.144410e+08

In [241]:
merged_customer_loan=customer.merge(loan[['customer_id','loan_id','requested_loan_amount','approved_loan_amount']],on='customer_id',how='left')
merged_customer_loan=merged_customer_loan[~merged_customer_loan['loan_id'].isna()]
income_segment_loan_analysis=merged_customer_loan.groupby('income_segment').agg(
    total_application_incomewise=('loan_id','nunique'),
    total_req_loan_incomewise=('requested_loan_amount','sum'),
    total_app_loan_incomewise=('approved_loan_amount','sum')
)
income_segment_loan_analysis

,total_application_incomewise,total_req_loan_incomewise,total_app_loan_incomewise
income_segment,,,
High,1842,3.618605e+09,2.681631e+09
Low,2673,1.503399e+09,9.618019e+08
Mid,2896,3.112679e+09,2.164703e+09
Premium,589,1.909230e+09,1.501125e+09

In [242]:
employment_analysis = loan.groupby('employment_type').agg(
    no_of_applications=('loan_id', 'count'),
    total_requested_amount=('requested_loan_amount', 'sum'),
    total_approved_amount=('approved_loan_amount', 'sum')
).sort_values(
    'no_of_applications',
    ascending=False
)

employment_analysis

,no_of_applications,total_requested_amount,total_approved_amount
employment_type,,,
Salaried,4597,5.658138e+09,4.101110e+09
Self-employed,1263,1.715822e+09,1.256096e+09
Business,1060,1.768653e+09,1.319632e+09
Freelancer,729,7.605565e+08,5.228456e+08
Unemployed,351,2.407439e+08,1.095762e+08

In [252]:
loan['credit_score_category'] = pd.cut(
    loan['credit_score'],
    bins=[422, 579, 669, 739, 900],
    labels=['Poor', 'Fair', 'Good', 'Excellent']
)


credit_score_category_analysis=loan.groupby(['credit_score_category','loan_status'])['loan_id'].count().unstack()
credit_score_category_analysis

loan_status            Approved  Pending  Rejected
credit_score_category
Poor                        550        1       212
Fair                       2481        1       735
Good                       2234        3       395
Excellent                  1273        3       112

In [253]:
city_loan_analysis = loan.groupby('city').agg(
    no_of_applications=('loan_id', 'count'),
    total_requested_amount=('requested_loan_amount', 'sum'),
    total_approved_amount=('approved_loan_amount', 'sum')
).sort_values(
    'no_of_applications',
    ascending=False
)

city_loan_analysis

            no_of_applications  total_requested_amount  total_approved_amount
city
Chandigarh                 506             579536200.0            408532900.0
Vadodara                   458             642683200.0            469674300.0
Coimbatore                 450             594038500.0            419780600.0
Surat                      448             541526200.0            394336200.0
Ahmedabad                  443             583009300.0            424953400.0
Lucknow                    437             527916900.0            382167400.0
Pune                       419             521364600.0            380842400.0
Nagpur                     415             529150300.0            394726000.0
Patna                      414             537410300.0            365998700.0
Delhi                      407             463233700.0            320786600.0
Kolkata                    399             474456000.0            352920700.0
Chennai                    389             479903400.0            362955300.0
Ludhiana                   389             545857600.0            399164500.0
Jaipur                     379             511193700.0            372837100.0
Hyderabad                  369             452170200.0            306307700.0
Bhopal                     363             481584200.0            355895000.0
Indore                     350             463661900.0            327252600.0
Kanpur                     340             388214800.0            262163200.0
Bengaluru                  329             383668200.0            257010900.0
Mumbai                     296             443334000.0            350955700.0

In [254]:
loan_status_analysis = loan.groupby('loan_status').agg(
    no_of_loans=('loan_id', 'count'),
    total_requested_amount=('requested_loan_amount', 'sum'),
    total_approved_amount=('approved_loan_amount', 'sum')
)

loan_status_analysis

             no_of_loans  total_requested_amount  total_approved_amount
loan_status
Approved            6538            8.647233e+09           7.309261e+09
Pending                8            1.179320e+07           0.000000e+00
Rejected            1454            1.484887e+09           0.000000e+00

In [258]:
loan['EMI_Burden(%)']=(loan['emi_amount']/loan['monthly_income'])*100
loan['burden_type'] = np.where(
    loan['EMI_Burden(%)'] < 20,
    'Low',
    np.where(
        loan['EMI_Burden(%)'] <= 35,
        'Moderate',
        np.where(
            loan['EMI_Burden(%)'] <= 50,
            'High',
            'Very High'
        )
    )
)
loan

,loan_id,customer_id,application_date,loan_type,requested_loan_amount,approved_loan_amount,loan_tenure_months,interest_rate,monthly_income,monthly_expenses,...,credit_score,existing_loan_amount,loan_status,repayment_status,emi_amount,city,income_segment,credit_score_category,EMI_Burden(%),burden_type
0,LOAN007434,CUST002579,2023-01-01,Personal,252200.0,225800.0,7,13.28,21014.01,6544.62,...,680,34102.22,Approved,On-time,33700.77,Kanpur,Low,Good,160.372866,Very High
1,LOAN001381,CUST001547,2023-01-01,Personal,811500.0,734400.0,43,12.05,110163.49,26971.26,...,827,0.00,Approved,On-time,21115.20,Jaipur,High,Excellent,19.167149,Low
2,LOAN004633,CUST002304,2023-01-01,Gold,231100.0,185200.0,11,8.48,51653.29,35022.83,...,702,144230.00,Approved,Late,17558.60,Kanpur,Mid,Good,33.993188,Moderate
3,LOAN003608,CUST000872,2023-01-01,Business,4274200.0,3947300.0,118,11.91,142473.70,82212.72,...,776,442534.81,Approved,On-time,56927.13,Pune,High,Excellent,39.956238,High
4,LOAN000220,CUST002568,2023-01-01,Vehicle,1300500.0,1008700.0,30,9.97,112508.40,25798.71,...,712,105300.56,Approved,On-time,38126.30,Kanpur,High,Good,33.887514,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,LOAN000644,CUST000120,2024-12-30,Personal,385000.0,371600.0,41,12.98,35413.41,16459.62,...,710,0.00,Approved,Not Started,11269.35,Pune,Mid,Good,31.822267,Moderate
7996,LOAN005545,CUST000714,2024-12-30,Business,4630700.0,3385200.0,27,11.42,174055.54,60268.31,...,815,0.00,Approved,Not Started,142767.15,Ludhiana,High,Excellent,82.023905,Very High
7997,LOAN000605,CUST000991,2024-12-30,Gold,290000.0,254100.0,15,9.40,37443.51,19459.35,...,566,109566.59,Approved,Not Started,18020.90,Kolkata,Mid,Poor,48.128234,High
7998,LOAN006909,CUST001640,2024-12-30,Business,523700.0,0.0,119,12.00,58758.06,30760.40,...,756,543819.84,Rejected,Not Started,0.00,Nagpur,Mid,Excellent,0.000000,Low
7999,LOAN001171,CUST002088,2024-12-30,Home,7576200.0,6887000.0,117,8.52,126269.20,32879.83,...,750,68594.46,Approved,Not Started,86855.90,Delhi,High,Excellent,68.786292,Very High

In [259]:
repayment_analysis = loan.groupby('repayment_status').agg(
    no_of_loans=('loan_id', 'count'),
    total_loan_amount=('approved_loan_amount', 'sum')
).sort_values(
    'no_of_loans',
    ascending=False
)

repayment_analysis

                  no_of_loans  total_loan_amount
repayment_status
On-time                  5627       6.497874e+09
Not Started              1731       3.033366e+08
Late                      568       4.652495e+08
Default                    74       4.280080e+07

In [262]:
merge_rfm_loan=rfm.merge(loan,on='customer_id',how='left')
rfm_loan_analysis = merge_rfm_loan.groupby('segment').agg(
    no_of_customers=('customer_id', 'nunique'),
    no_of_loan_applications=('loan_id', 'count'),
    total_requested_amount=('requested_loan_amount', 'sum'),
    total_approved_amount=('approved_loan_amount', 'sum')
).sort_values(
    'no_of_loan_applications',
    ascending=False
)

rfm_loan_analysis

,no_of_customers,no_of_loan_applications,total_requested_amount,total_approved_amount
segment,,,,
Lost Customers,713,1924,2.528287e+09,1.831567e+09
Potential Loyalists,572,1576,1.905544e+09,1.383685e+09
At Risk Customers,480,1294,1.646972e+09,1.182830e+09
Champions,425,1107,1.780418e+09,1.319473e+09
Regular Customers,420,1070,1.113796e+09,7.854440e+08
Loyal Customers,389,1025,1.162786e+09,8.016754e+08